export const SOURCE_FOLDER_NOT_EXIST = 'Source folder does not exist, please create one.'
export const DESTINATION_EXIST = 'Destination exist. it would be overwrite.'
export const IMAGE_FOLDER_NOT_EXIST = 'No image folder, some of image may not show on rendered page.'
export const COULD_NOT_COPY_IMAGE = 'Could not copy image folder.'
export const CSS_COPY_ERROR = 'CSS compiling error.'
